version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - data:/data/db


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongoadmin:mypassword@mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  data:
    driver: local